FROM node:21-alpine
RUN apk add --no-cache git
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY docusaurus.config.js sidebars.js ./
COPY src/ ./src/
COPY static/ ./static/
COPY docs/ ./docs/
COPY blog/ ./blog/
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "serve", "--", "--host", "0.0.0.0", "--port", "3000", "--build", "--dir", "build"]
